// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaMSFauzbpLyoo6a7cyE3rRPHkHsZ6pPc',
    appId: '1:593729965156:web:b579054cfceafa9820a371',
    messagingSenderId: '593729965156',
    projectId: 'bookforumbrademo',
    authDomain: 'bookforumbrademo.firebaseapp.com',
    storageBucket: 'bookforumbrademo.firebasestorage.app',
    measurementId: 'G-K7J496P4GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbmkHtbOcZb3ZG4hktb-lKn50mD08_6Ks',
    appId: '1:593729965156:android:1437afbe6558f73d20a371',
    messagingSenderId: '593729965156',
    projectId: 'bookforumbrademo',
    storageBucket: 'bookforumbrademo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP5FbZxuTTi9Sb3M_BHkRzr_nJfIKxk0o',
    appId: '1:593729965156:ios:6b870a84cd29fee920a371',
    messagingSenderId: '593729965156',
    projectId: 'bookforumbrademo',
    storageBucket: 'bookforumbrademo.firebasestorage.app',
    iosBundleId: 'com.example.forumLivros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP5FbZxuTTi9Sb3M_BHkRzr_nJfIKxk0o',
    appId: '1:593729965156:ios:6b870a84cd29fee920a371',
    messagingSenderId: '593729965156',
    projectId: 'bookforumbrademo',
    storageBucket: 'bookforumbrademo.firebasestorage.app',
    iosBundleId: 'com.example.forumLivros',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaMSFauzbpLyoo6a7cyE3rRPHkHsZ6pPc',
    appId: '1:593729965156:web:08b3b3493ba6216620a371',
    messagingSenderId: '593729965156',
    projectId: 'bookforumbrademo',
    authDomain: 'bookforumbrademo.firebaseapp.com',
    storageBucket: 'bookforumbrademo.firebasestorage.app',
    measurementId: 'G-7FY3G9QEZZ',
  );

}